site_name: Diretoria Central de Monitoramento da Execução Física e Orçamentária
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: deep purple
  font:
      text: Roboto
      code: Roboto Mono

plugins:
  - blog